<a href="https://colab.research.google.com/github/SeungHyunKee/PracticeCoding/blob/main/linear01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.linalg as nla

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[10,20,30], [40,50,60], [70,80,100]])

# print(A)
# print(B)

# print(A+B)
# print(A-B)
print(np.matmul(A,B))  # 같은자리의 곱이 아닌, 행렬곱하기를 한 결과!
print(np.matmul(A, nla.inv(B)))  # A 와 B의 inverse의 곱

# 행렬식 구하기 det
print(nla.det(A)) # 0 => A 는 singular 하다는것 즉, 역행렬이 없다는것
print(nla.det(B))


[[ 300  360  450]
 [ 660  810 1020]
 [1020 1260 1590]]
[[ 1.00000000e-01 -5.55111512e-17  0.00000000e+00]
 [-1.66533454e-16  1.00000000e-01  0.00000000e+00]
 [-1.00000000e-01  2.00000000e-01  0.00000000e+00]]
0.0
-2999.9999999999977


In [ ]:
import sympy as sp

# sp : 행렬로 쓰라고 만들어놓은 클래스
# Matrix() 안에 넣으면 행렬로 생각을 한다
sp_A = sp.Matrix([[1,2,3], [4,5,6], [7,8,9]])
sp_B = sp.Matrix([[10,20,30], [40,50,60], [70,80,100]])

# display() = 웹에 적합한 방법으로 출력하라는것(문자열 형식이아닌, html형식)
display(sp_A + sp_B)
display(sp_A - sp_B)
display(sp_A * sp_B)
display(sp_A * sp_B.inv())
display(sp_A.det())
display(sp_B.det())


Matrix([
[11, 22,  33],
[44, 55,  66],
[77, 88, 109]])

Matrix([
[ -9, -18, -27],
[-36, -45, -54],
[-63, -72, -91]])

Matrix([
[ 300,  360,  450],
[ 660,  810, 1020],
[1020, 1260, 1590]])

Matrix([
[ 1/10,    0, 0],
[    0, 1/10, 0],
[-1/10,  1/5, 0]])

0

-3000

In [ ]:
A = sp.Matrix([ [1,-2], [1,-1], [1,0], [1,2]])
b = sp.Matrix([4,3,1,0])
# display(A)
# display(b)

# A 의 sudo inverse 구하기 = A.pinv()
display(A.pinv())
# A의 transpose = A.T
display((A.T * A).inv()*A.T) # => A.pinv()

x = A.pinv() * b
display(x) # 61/35, -36/35

# 주어진 문제에서 가장 근접한 직선구하기
# (-36/35)t + (61/35) = b

# b를 projection한 point값 구하는 방법 : p = Pb = Ax
display(A*x)
# -> 원래 b의 projection은 [4,3,1,0]이었는데, 이를 행렬 A에대해 column splace로 projection한 값

Matrix([
[ 1/5,  8/35, 9/35, 11/35],
[-1/5, -3/35, 1/35,  9/35]])

Matrix([
[ 1/5,  8/35, 9/35, 11/35],
[-1/5, -3/35, 1/35,  9/35]])

Matrix([
[ 61/35],
[-36/35]])

Matrix([
[  19/5],
[ 97/35],
[ 61/35],
[-11/35]])